### ISSUE TITLE
Areas of improvement

### ISSUE THREAD

**Issue by Kingjosh007** [Vagyasri/Cuisine-variant#22]
Hi @Ugboaja-Uchechi and @Vagyasri. 
Thanks for submitting your code for review. You did a great job in setting up everything. Kudos to you for the automation in moving the tasks. 
However, there are a few changes you may want to consider:

- Kindly rename your repo from `Kanban` to something more self-explanatory, because this project is not only about the Kanban, but mostly about working with an API.

- In your package.json file, kindly rename all the occurrences of `Webpack-Setup` to your actual repo's name. We could see that you copied it from a previous repo and you just omitted to update the file.

- **[OPTIONAL]**  You may want to add a **deploy** script to your package.json scripts, following the instructions given in [this article](https://survivejs.com/webpack/techniques/deploying/)

**Comment by Vagyasri** [comment]
Done the needful.
